schema: [schema.docs.graphql, local-schema.graphql]
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://api.github.com/graphql
      headers:
        user-agent: JS GraphQL
        authorization: 'Bearer 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'
      introspect: false
